version: '3'
services:
  api:
    build: .
    environment:
      - REDIS_ADDR=redis:6379
      - STORE_PORT=:8080
    ports:
      - "8080:8080"
  redis:
    image: "redis:7.0.7"
    ports:
      -  6379

