---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: lang
  labels:
    app: api
spec:
  ports:
    - port: 8080
  selector:
    app: api
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: lang
  labels:
    app: api
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - image: docker.io/tnosaj/lang-api:latest
        imagePullPolicy: Always
        name: api
        env:
        - name: REDIS_ADDR
          value: redis.lang:6379
        - name: REDIS_PASS
          valueFrom:
            secretKeyRef:
              name: lang-secrets
              key: redis
        ports:
        - containerPort: 8080
          name: api
