apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: lang
  labels:
    app: redis
spec:
  ports:
    - port: 6379
  selector:
    app: redis
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pv-claim
  namespace: lang
  labels:
    app: redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: lang
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  serviceName: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: redis:7.0.7
        name: redis
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: lang-secrets
              key: redis
        args: ["--maxmemory", "64Mb","--requirepass","$(REDIS_PASSWORD)"]
        ports:
        - containerPort: 6379
          name: redis
        volumeMounts:
        - name: redis-persistent-storage
          mountPath: /var/lib/redis
      - image: oliver006/redis_exporter
        name: exporter
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: lang-secrets
              key: redis
        ports:
        - containerPort: 9121
          name: exporter
      volumes:
      - name: redis-persistent-storage
        persistentVolumeClaim:
          claimName: redis-pv-claim
